[package]
name = "rosthem-dto"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
prisma = "0.1"
angular-units = "0.2" # for prisma TODO: Remove